
#todo make reading variables more generic, so that execution does not depend on specific file's content

- name: Get hierarchy file content
  command: "cat {{ hierarchy_file_path }}"
  register: hierarchy_file_content
  ignore_errors: true
  changed_when: false
  when: 
    - hierarchy_file_path is defined
    - ansible_os_family == 'RedHat' or ansible_os_family == 'Debian'

- name: Get file content
  win_shell: "type {{ hierarchy_file_path }}"
  register: hierarchy_file_content
  ignore_errors: true
  changed_when: false
  when: 
    - hierarchy_file_path is defined
    - ansible_os_family == 'Windows'

- name: Print hierarchy_file_content
  ansible.builtin.debug:
    msg: "hierarchy_file_content is '{{ hierarchy_file_content }}'."

- name: Set values based on hierarchy information
  set_fact:
    hierarchy_department: "{{ hierarchy_file_content.stdout | regex_search('department:.*\"(.*)\"', '\\1') | default('unknown', boolean=True) }}"
  ignore_errors: true
  when: 
    - hierarchy_file_content.stdout is defined  

#This is always defined
- name: Set values based on OS 
  set_fact:
    hierarchy_os:  "{{ansible_os_family}}"
  ignore_errors: true

- name: Set values based on hierarchy information
  set_fact:
    hierarchy_tcs: "{{ hierarchy_file_content.stdout | regex_search('tcs:.*\"(.*)\"', '\\1') | default('unknown', boolean=True) }}"
  ignore_errors: true
  when: 
    - hierarchy_file_content.stdout is defined 

# need to think of how to include PAAS - is there a nicer way than below?
- name: Set values based on hierarchy information
  set_fact:
    hierarchy_paas: "PAAS|" # Pipe has to be included here in case support group is false (which means hierarchy_final won't end in |)
  ignore_errors: true
  when: 
    - is_support_group_paas is true

- name: Set values based on hierarchy information
  set_fact:
    hierarchy_paas: ""
  ignore_errors: true
  when: 
    - is_support_group_paas is false

- name: Merge variables
  set_fact: 
      hierarchy_final: "{{hierarchy_department}}|{{hierarchy_os}}|{{hierarchy_tcs}}|{{hierarchy_paas}}"
  when: 
    - hierarchy_file_content.stdout is defined 

- name: Print hierarchy_final
  ansible.builtin.debug:
    msg: "{{ hierarchy_final }}"
  when: 
    - hierarchy_final is defined 

#Hierarchy defined in Machine-agent-controller-info.xml 
- name: Update Machine Agent Hierarchy values - Linux OS
  become: true
  template:
    src: templates/machine-agent-controller-info.xml.j2
    dest: '{{ machine_agent_dest_folder_linux }}/conf/controller-info.xml'
    owner: "{{ appdynamics_user }}"
    group: "{{ appdynamics_user }}"
    mode: 0755
  changed_when: false
  when: 
    - hierarchy_final is defined
    - ansible_os_family == 'RedHat' or ansible_os_family == 'Debian'

- name: Update Machine Agent Hierarchy values - Win OS
  template:
    src: templates/machine-agent-controller-info.xml.j2
    dest: '{{ machine_agent_dest_folder_win }}/conf/controller-info.xml'
    force: yes
  changed_when: false
  when: 
    - hierarchy_final is defined
    - ansible_os_family == 'Windows'

      