---
# tasks file for configuration

- name: Controller URL must be provided
  fail:
    msg: "The variable 'controller_host_name' is empty"
  when: (controller_host_name is not defined) or (controller_host_name|length == 0)

- name: Token value must be provided
  fail:
    msg: "The variable 'controller_access_token' is empty"
  when: (controller_access_token is not defined) or (controller_access_token|length == 0)

- name: Include infra vars
  include_vars: health_rules_definitions_infra.yml
  when: import_infra_health_rules|default(false)|bool == true

- name: Include import infra health rules tasks
  include_tasks: import_infra_health_rules.yml
  vars:
    hierarchy_item: "{{ outer_item }}"
    application_id: "{{ infra_application_id }}"
  with_items: "{{ health_rule_hierarchy }}"
  loop_control:
    loop_var: outer_item
  when: import_infra_health_rules|default(false)|bool == true

- name: Include java app vars
  include_vars: health_rules_definitions_java_app.yml
  when: import_java_app_health_rules|default(false)|bool == true

- name: Include import Java application health rules tasks
  include_tasks: import_java_app_health_rules.yml
  vars:
    application_id: "{{ java_application_id }}"
  with_items: "{{ java_application_ids }}"
  loop_control:
    loop_var: java_application_id
  when: import_java_app_health_rules|default(false)|bool == true

- name: Include import dashboards tasks
  include_tasks: import_dashboards.yml
  when: import_dashboards|default(false)|bool == true